### ISSUE TITLE
Doesn't work in built Mode

### ISSUE THREAD

**Issue by tarrabass** [keijiro/MidiKlak#3]
it work perfectly in editor mode but not in built mode ?

**Comment by keijiro** [comment]
Did you close Unity Editor before running the build? Unity Editor should be closed before running the standalone build because MIDI devices are exclusively retained by a single application on some systems.

**Comment by tarrabass** [comment]
Yes it's working, it was cause the editor open, you are right.
Thanks you so much for all your work 
you make my life easier!!! i make realltime content for 12m fulldome environment 
you'll recognise some of your work 
https://photos.google.com/share/AF1QipODRDNubeJTE4zAcXvNSPHajtzNtyK5tfzCweznN-PMFRm4gNrhy9SaQC4pzQg2cQ?key=LXBjekQ5NTZaQVZrRy1TS1pBclB2QURGWWJYTDVn
