### ISSUE TITLE
Latency issue with E-DRUM 

### ISSUE THREAD

**Issue by duanluoo** [keijiro/MidiKlak#4]
HELLO    Keijiro: )

Having fun with you work, appreciate. but got a little problem there. 
when i trigger the midi event with my E-DRUM used your library, seem like i got about 200ms Latency in my project. I am sure that is not a midi signal Latency but maybe some unity optimization that i am not familiar with . Love to hear some suggestion from you, my friend.
                                                                                               cheers~

**Comment by keijiro** [comment]
I'm pretty sure that there is no latency problem with MIDI signals, and guessing that the latency is happened in rendering. I'd recommend checking if it has the same latency with a minimum project.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
